env:
  global:
    - TERM=dumb
    - secure: GiBycx982SBwBx6vA0bFjdvYIxqOU3GMRu6fWBfN8fkYVSnfycFRObnXmho0WOXYdrti3bhWOq1aM1Qc3mNFRy3yyMynPUrsQfo8eFqTg7Ch/tUPxEvlcPhBw77y31egsiQQ+SanWJxiQvAfYW5tcbXOVZq4BIwP0QqH02ZkpScPWc2QxEjJnfWkk/AiAdc3pWsU2NTf2Dvqe7YLuw9siG1RmteEj/GKzz8Z7Y8Vw3S41H6ARqMonfIARB/dzbM3PuVU+0A/IFs9PnIPDjdhXxgSkppqxBL6ur+IYLJ5Fy/xCVDfyKq4AU54+e2XFU2PSuS1N0Uskg7YWy8mg89zM1ZocZ+YV0T7R+sGj7IaTtYQ82QQtXW/AMFzclG54PtSFsauznLYt1n7bs7+iDYxewhfMahFwEuB3wYqz3oAa7bEMthSZNtBQVZFZqnCHs8EosIbG4ZkIwrxdUhxivGseKJAqMZSmcweMZTkIFijyMkPC4lZxDVIZZ0kYjELNGTIVx8j+YSKCgdrT/cLArjHHI8P5uDZnWiu2+1mmtq8dqHrFMRHOm9tETic6gbGMa54mFZnxHEqw4nwgsjQyV709JhHQVO/j39sp2tnMz3tOgePpsV1x35BXgbzONI5dNDI6ITCcGx88gnVwQN6jrvdLpy1mugryTaOlBlnTm7+hj8=
dist: xenial
git:
  quiet: true
  depth: 1
notifications:
  email: false
language: java
jdk: openjdk8
node_js: lts/*
python: 3
service:
  - docker
addons:
  apt:
    update: true
    packages:
      - sudo
      - lsof
      - wget
      - bash
      - curl
      - jq
      - libxml2-utils
      - unzip
      - docker-ce
      - python3-dev
      - python3-pip
      - python3-six
      - python3-setuptools
install: true
before_install:
  - docker-compose -v
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user $(whoami) --upgrade pip >/dev/null # pip3 -> pip
  - pip install --user $(whoami) --upgrade docker-compose httpie >/dev/null 2>&1
  - http --version --debug
  #- docker system prune -af --volumes
  - docker-compose -v
  #- pip install --user $(whoami) --upgrade docker-compose httpie >/dev/null 2>&1
  #- docker-compose -v
  - source <(curl -fsSL https://raw.github.com/daggerok/bash-functions/master/main.bash)
  - stop_any 80 8080 5672 5432 27017 >/dev/null
jobs:
  include:
    - stage: test
      jdk: openjdk8
      name: integration tests with docker-compose
      script:
        - cd $TRAVIS_BUILD_DIR && ./gradlew
        - cd $TRAVIS_BUILD_DIR && ./gradlew composeUp
        - wait_for 8080
        - http :8080
        - http :8080/api/mvc
        - http :8080/api/mvc body="hello mvc"
        - http :8080/api/mvc/tags
        - cd $TRAVIS_BUILD_DIR && ./gradlew composeDown
        - stop_any 80 8080
    - stage: test
      jdk: openjdk8
      name: integration tests
      script:
        - cd $TRAVIS_BUILD_DIR && ./gradlew
        - java -jar $TRAVIS_BUILD_DIR/build/libs/*.jar &
        - wait_for 8080
        - http :8080
        - http :8080/api/mvc
        - http :8080/api/mvc body="hello mvc"
        - http :8080/api/mvc/tags
        - stop_any 80 8080
    - stage: test
      jdk: openjdk11
      name: integration tests (openjdk11)
      script:
        - cd $TRAVIS_BUILD_DIR && ./gradlew
        - java -jar $TRAVIS_BUILD_DIR/build/libs/*.jar &
        - wait_for 8080
        - http :8080
        - http :8080/api/mvc
        - http :8080/api/mvc body="hello mvc"
        - http :8080/api/mvc/tags
        - stop_any 80 8080
    - stage: test
      jdk: openjdk8
      name: integration tests with docker-compose
      script: cd $TRAVIS_BUILD_DIR && ./gradlew dependencyUpdates
    - stage: deploy
      jdk: openjdk11
      name: GitHub release and GitHub pages deployment (openjdk11)
      script: skip
      if: branch = "master" AND type NOT IN (pull_request)
      before_deploy:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ ".$TRAVIS_BRANCH" != ".master" ] ; then exit 0 ; fi
        - env
        # documentation
        - cd $TRAVIS_BUILD_DIR && ./gradlew npm_run_gh-pages
      deploy: &pages
        provider: pages
        skip-cleanup: true
        github-token: "$GITHUB_TOKEN"
        keep-history: true
        local-dir: $TRAVIS_BUILD_DIR/.vuepress/dist
        target_branch: gh-pages
        on:
          branch: master
          condition: "$TRAVIS_PULL_REQUEST = false"
cache:
  directories:
    - $TRAVIS_BUILD_DIR/node_modules
    - ~/.gradle
    - ~/.m2
  packages: true
  pip: true
